### ISSUE TITLE
请问下这个怎么使用？

### ISSUE THREAD

**Issue by 1198560751** [gfreezy/mailhook#1]
请问下这个怎么使用？

**Comment by gfreezy** [comment]
代码有点老，飞书接口升级后应该是没法用了

**Comment by 1198560751** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gfreezy/mailhook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gfreezy/mailhook] 请问下这个怎么使用？ (Issue #1)





 
代码有点老，飞书接口升级后应该是没法用了

**Comment by gfreezy** [comment]
你是要把邮件转到飞书机器人？

**Comment by 1198560751** [comment]
是的，转到机器人然后发到群组




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gfreezy/mailhook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月4日(星期四) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gfreezy/mailhook] 请问下这个怎么使用？ (Issue #1)





 
你是要把邮件转到飞书机器人？

**Comment by gfreezy** [comment]
代码更新了，README 补充了文档。现在也支持把附件发送到飞书
